services:
  - type: web
    name: angular-quest-socket
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm run socket
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ALLOWED_ORIGINS
        sync: false
